name = "gbr_mcp"
version = "1.0.0-alpha"

description = "MCP (Model Context Protocol) is an open-source standard for connecting AI applications to external systems."
repository = { type = "github", user = "gleam-br", repo = "gbr_mcp" }
licences = ["Apache-2.0"]
links = []

[dependencies]
gleam_stdlib = "~> 0.71"
gleam_json = "~> 3.1"

simplifile = "~> 2.3"

gbr_json = { path = "../gbr_json" }

[dev-dependencies]
gleeunit = "~> 1.9"
